### ISSUE TITLE
Error:'ZoomTransition' cannot be constructed because it has no accessible initializers

### ISSUE THREAD

**Issue by Vienta** [tristanhimmelman/ZoomTransition#2]
Hi,

```
if let navigationController = self.navigationController {
        self.animationController = ZoomTransition(navigationController: navigationController) as! ZoomTransition
}
self.navigationController?.delegate = animationController
```

**Comment by M1ndaugasJ** [comment]
facing the same issue

edit: make the initializer in ZoomTransition.swift public, this solves the issue

**Comment by tristanhimmelman** [comment]
Hmm that's odd. I'm not sure why this error is happening.

I have just released a new version with Swift 2.0 support which may have been the problem. Please get the latest and let me know if you are still having a problem.

**Comment by dtfiedler** [comment]
still experiencing this issue. any ideas?

edit: changing initializer to public fixed the issue as mentioned above

**Comment by whisper-bye** [comment]
+1

``` swift
public init(navigationController: UINavigationController) {
    self.navigationController = navigationController
}
```

**Comment by tristanhimmelman** [comment]
I have just released a new version with the above PR fix.

Thanks everyone
